### ISSUE TITLE
Local Dev Environment Sonar Setup for Static Code Analysis

### ISSUE THREAD

**Issue by idemiapune** [idemiapune/extoauth#9]

**Comment by govindraj-shinde** [comment]
# Pre requisites 

1. IDE like Eclipse or IntelliJ
2. Java Maven Project with Some or no Junit test cases
3. Apache Maven

# Steps to Set up on local environment

1. Download the latest ( LTS- 6.7.3) for the SonarQube [SonarQube](https://www.sonarqube.org/#_)
2. In your Maven project, add the below plugins in pom.xml

```xml
           <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.1</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.18</version>
                </plugin>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>3.3.0.603</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.7.9</version>
                </plugin>
           </plugins>
```

**Comment by govindraj-shinde** [comment]
We can even configure our project online as well to identify the Static analysis of our code
For that we should have

- git account
- Project hosted on git-hub

# Steps to configure our project on Sonar Cloud
1. Click on the link [Sonar Cloud](https://about.sonarcloud.io/sq/)
2. Choose Git-Hub , enter your login credentials
3. Choose Analyse new Project link
4. Choose My Personal Organization
5. Continue and put your token (put any name)
6. Generate
7. You will a window , which will have a mvn command set.
8. Copy the command from the page and run that into your project (present on your local machine) from the command line.

<img width="1282" alt="screen shot 2018-05-28 at 7 02 11 pm" src="https://user-images.githubusercontent.com/22301104/40616727-aee5ccd0-62a9-11e8-806d-722514de15ae.png">

**Comment by govindraj-shinde** [comment]
Task closed
